// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTpBsQN39ZIY7yoc6k23H_35WtzVzCNdQ',
    appId: '1:832671561697:web:15d54c993b1ea0b3f384a0',
    messagingSenderId: '832671561697',
    projectId: 'responsivedesign-f0c28',
    authDomain: 'responsivedesign-f0c28.firebaseapp.com',
    storageBucket: 'responsivedesign-f0c28.firebasestorage.app',
    measurementId: 'G-QMXF5BK09E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSpXOLaw36w9JcMvbd00b0kuhmLOyTPC0',
    appId: '1:832671561697:android:0f45e8ab38173aedf384a0',
    messagingSenderId: '832671561697',
    projectId: 'responsivedesign-f0c28',
    storageBucket: 'responsivedesign-f0c28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_M0PpgT1a-z52_1uP6y0ByPcCnyV5Lso',
    appId: '1:832671561697:ios:e4b58909cbddbd0af384a0',
    messagingSenderId: '832671561697',
    projectId: 'responsivedesign-f0c28',
    storageBucket: 'responsivedesign-f0c28.firebasestorage.app',
    iosBundleId: 'com.example.responsiveDesign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_M0PpgT1a-z52_1uP6y0ByPcCnyV5Lso',
    appId: '1:832671561697:ios:e4b58909cbddbd0af384a0',
    messagingSenderId: '832671561697',
    projectId: 'responsivedesign-f0c28',
    storageBucket: 'responsivedesign-f0c28.firebasestorage.app',
    iosBundleId: 'com.example.responsiveDesign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTpBsQN39ZIY7yoc6k23H_35WtzVzCNdQ',
    appId: '1:832671561697:web:037e543ef89c12f5f384a0',
    messagingSenderId: '832671561697',
    projectId: 'responsivedesign-f0c28',
    authDomain: 'responsivedesign-f0c28.firebaseapp.com',
    storageBucket: 'responsivedesign-f0c28.firebasestorage.app',
    measurementId: 'G-PJHH4XJPH6',
  );
}
